In [1]:
import requests 
import pandas as pd
from bs4 import BeautifulSoup
import bs4

# 球員個人紀錄 個人成績表 陳鏞基 三壘手
#url = "http://www.cpbl.com.tw/players/person.html?player_id=L0K0&teamno=L01"
# 球員個人紀錄 個人成績表 官大元 投手
url = "http://www.cpbl.com.tw/players/person.html?player_id=R139&teamno=E02"
# 球員個人紀錄 個人成績表 江坤宇 游擊手
#url = "http://www.cpbl.com.tw/players/person.html?player_id=004636&teamno=E02"
# 球員個人紀錄 個人成績表 周思齊 左外野手
#url = 'http://www.cpbl.com.tw/players/person.html?player_id=G072&teamno=E02'
# 球員個人紀錄 個人成績表 蘇俊璋 投手 
#url ='http://www.cpbl.com.tw/players/person.html?player_id=005558&teamno=AJL011'

response = requests.get(url)


if response.status_code != 200:
    print(print('URL發生錯誤：' + url))
    
soup = BeautifulSoup(response.text, 'html.parser')

In [2]:
df_battling = pd.DataFrame() # dict 打擊成績 
df_pitching = pd.DataFrame() # dict 投手成績
df_fielding = pd.DataFrame() # dict 守備成績
df_battler_against = pd.DataFrame() # dict 打者對戰成績
df_pitcher_against = pd.DataFrame() # dict 投手對戰成績



tables = soup.find_all("table")
for table in tables[1:]:
    trs = table.find_all("tr")
        # 抓columns
    for tr in trs:
        txs = [tx.text for tx in tr.children if tx != "\n" and not isinstance(tx, bs4.element.Comment)]       
        
        
        if txs[0] == "YEAR" and txs[-1] == "SSA":           
            
            # dict 打擊成績 
            for col in txs:
                df_battling[col] = ""
        
        elif txs[0] == "YEAR" and txs[-1] == "G/F":        
            # dict 投手成績
            for col in txs:
                df_pitching[col] = ""
            
        elif txs[0] == "YEAR" and txs[-1] == "POS":           
            # dict 守備成績
            for col in txs:
                df_fielding[col] = ""
             
        elif txs[0] == "YEAR" and txs[-1] == "FPCT":          
            # dict 歷年守備成績  
            pass
        
        elif txs[0] == "TEAM" and txs[-1] == "SSA": 
            #dict 打者對戰成績 
            for col in txs:
                df_battler_against[col] = ""
        elif txs[0] == "TEAM" and txs[-1] == "ER": 
            #dict 投手對戰成績 
            for col in txs:
                df_pitcher_against[col] = "" 

df_list  = [df_battling, df_pitching, df_fielding, df_battler_against, df_pitcher_against]

In [3]:
tables = soup.find_all("table")
for table in tables[1:]:
    trs = table.find_all("tr")
    columns = [th.text for th in trs[0].find_all("th")]
    
    for df in df_list:
        if columns == list(df.columns):
            for tr in trs:
                tds = [td.text.strip() for td in tr.find_all("td")]
                if len(columns) == len(tds) and tds[0] != "TOTAL" and tds != columns :
                    df.loc[len(df)] = tds

In [4]:
df_battling

,YEAR,TEAM,G,PA,AB,RBI,R,H,1B,2B,...,BB,IBB,HBP,CS,GO,AO,G/F,SB%,TA,SSA
0,2019,中信兄弟,2,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0.000,0.00,0.000,0

In [5]:
df_pitching

,YEAR,TEAM,G,GS,GR,CG,SHO,NBB,W,L,...,IBB,HBP,SO,WP,BK,R,ER,GO,AO,G/F
0,2011,兄弟,45,3,42,0,0,0,10,5,...,3,7,91,6,1,51,44,133,110,1.209
1,2012,兄弟,57,0,57,0,0,0,11,3,...,0,5,56,6,0,51,47,115,88,1.307
2,2013,兄弟,65,2,63,0,0,0,7,5,...,1,2,57,3,0,31,26,98,118,0.831
3,2014,中信兄弟,33,0,33,0,0,0,1,2,...,0,0,19,0,0,22,21,35,43,0.814
4,2015,中信兄弟,59,0,59,0,0,0,4,2,...,0,5,36,2,0,25,24,68,68,1.000
5,2016,中信兄弟,34,0,34,0,0,0,3,3,...,3,2,29,4,0,44,38,33,56,0.589
6,2017,中信兄弟,12,0,12,0,0,0,0,0,...,0,2,10,2,0,14,14,13,17,0.765
7,2018,中信兄弟,27,0,27,0,0,0,3,1,...,2,1,22,2,0,21,17,35,37,0.946
8,2019,中信兄弟,41,0,41,0,0,0,1,1,...,1,3,20,1,0,31,29,75,59,1.271
9,2020,中信兄弟,1,0,1,0,0,0,0,0,...,0,0,0,0,0,2,2,1,1,1.000
10,2006,代訓藍隊,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,2,1,2.000
11,2012,兄弟二軍,1,0,1,0,0,0,0,0,...,0,0,1,0,0,3,3,3,0,0.000
12,2014,中信兄弟二軍,5,0,5,0,0,0,0,0,...,0,2,8,1,0,5,4,8,8,1.000
13,2016,中信兄弟二軍,8,0,8,0,0,0,0,1,...,0,0,7,0,0,4,3,7,11,0.636
14,2017,中信兄弟二軍,18,0,18,0,0,0,3,2,...,0,4,20,1,0,13,11,15,23,0.652
15,2018,中信兄弟二軍,16,0,16,0,0,0,2,0,...,0,2,9,0,0,3,0,14,19,0.737
16,2019,中信兄弟二軍,3,0,3,0,0,0,0,0,...,0,1,0,0,0,0,0,5,4,1.250
17,2020,中信兄弟二軍,9,0,9,0,0,0,3,0,...,0,1,5,0,0,0,0,16,11,1.455

In [6]:
df_fielding

    YEAR    TEAM   G  TC PO   A  E DP TP   FPCT POS
0   2011      兄弟  45  35  9  21  5  0  0  0.857  詳細
1   2012      兄弟  57  24  6  17  1  2  0  0.958  詳細
2   2013      兄弟  65  17  3  14  0  1  0  1.000  詳細
3   2014    中信兄弟  33  14  4   9  1  1  0  0.929  詳細
4   2015    中信兄弟  59  13  8   5  0  3  0  1.000  詳細
5   2016    中信兄弟  34   7  2   5  0  1  0  1.000  詳細
6   2017    中信兄弟  12   6  5   0  1  0  0  0.833  詳細
7   2018    中信兄弟  27   7  4   3  0  2  0  1.000  詳細
8   2019    中信兄弟  41  16  8   7  1  1  0  0.938  詳細
9   2020    中信兄弟   1   0  0   0  0  0  0  0.000  詳細
10  2006    代訓藍隊   1   0  0   0  0  0  0  0.000  詳細
11  2012    兄弟二軍   1   2  0   2  0  0  0  1.000  詳細
12  2014  中信兄弟二軍   5   2  0   2  0  1  0  1.000  詳細
13  2016  中信兄弟二軍   8   1  0   1  0  0  0  1.000  詳細
14  2017  中信兄弟二軍  18   3  0   3  0  0  0  1.000  詳細
15  2018  中信兄弟二軍  16   4  1   2  1  1  0  0.750  詳細
16  2019  中信兄弟二軍   3   1  0   1  0  0  0  1.000  詳細
17  2020  中信兄弟二軍   9   3  2   1  0  0  0  1.000  詳細

In [7]:
df_battler_against

Empty DataFrame
Columns: []
Index: []

In [8]:
df_pitcher_against

,TEAM,GS,GR,CG,SHO,W,L,SV,BS,HLD,...,H,HR,BB,IBB,HBP,SO,WP,BK,R,ER
0,富邦,0,24,0,0,1,0,0,1,4,...,43,5,11,0,2,19,3,0,27,25
1,Lamigo,1,120,0,0,12,8,2,7,23,...,179,19,45,3,11,103,10,0,96,87
2,義大,1,52,0,0,5,5,2,2,11,...,75,13,18,1,1,30,1,0,39,35
3,興農,1,35,0,0,8,3,0,2,2,...,80,2,28,1,3,44,3,1,30,26
4,統一7-ELEVEn,2,138,0,0,14,6,1,3,24,...,208,24,58,5,10,144,9,0,100,89